### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ahoarau** [LouisCharlesC/safe#2]
1. A method to **replace** the protected variable : 
```c++
safe::Safe<int> m_count{0};
m_count = 20; // equivalent to *m_count.access() = 20;
````
2. A method to get a **copy** of the protected variable : 
```c++
safe::Safe<int> m_count{0};
auto count_copy = m_count.getCopy(); // equivalent to auto copy = *m_count.access();
````

**Comment by LouisCharlesC** [comment]
These suggestions will not be integrated into *safe*, because the primary purpose of *safe* is to force the programmer to either write *access* or *unsafe*. However, I am working on a small wrapper class I call State that provides a simple *set*, *get*, etc. interface for shared objects. This will be part of my *mess* repo.
